[2024-06-19T03:45:11.174+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T03:45:11.211+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract_data_from_postgres.extract_data scheduled__2024-06-18T00:00:00+00:00 [queued]>
[2024-06-19T03:45:11.224+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract_data_from_postgres.extract_data scheduled__2024-06-18T00:00:00+00:00 [queued]>
[2024-06-19T03:45:11.225+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-06-19T03:45:11.249+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data> on 2024-06-18 00:00:00+00:00
[2024-06-19T03:45:11.260+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8229) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T03:45:11.263+0000] {standard_task_runner.py:63} INFO - Started process 8231 to run task
[2024-06-19T03:45:11.264+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'extract_data_from_postgres', 'extract_data', 'scheduled__2024-06-18T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/extract_data_from_postgres.py', '--cfg-path', '/tmp/tmp5inzgbsj']
[2024-06-19T03:45:11.267+0000] {standard_task_runner.py:91} INFO - Job 9: Subtask extract_data
[2024-06-19T03:45:11.352+0000] {task_command.py:426} INFO - Running <TaskInstance: extract_data_from_postgres.extract_data scheduled__2024-06-18T00:00:00+00:00 [running]> on host 7709186783c9
[2024-06-19T03:45:11.492+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='candratama' AIRFLOW_CTX_DAG_ID='extract_data_from_postgres' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-18T00:00:00+00:00'
[2024-06-19T03:45:11.494+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T03:45:11.555+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T03:45:11.570+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/extract_data_from_postgres.py", line 15, in extract_data_from_postgres
    connection = postgres_hook.get_conn()
                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 145, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 519, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `***_db_conn` isn't defined
[2024-06-19T03:45:11.579+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=extract_data_from_postgres, task_id=extract_data, run_id=scheduled__2024-06-18T00:00:00+00:00, execution_date=20240618T000000, start_date=20240619T034511, end_date=20240619T034511
[2024-06-19T03:45:11.611+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 9 for task extract_data (The conn_id `***_db_conn` isn't defined; 8231)
[2024-06-19T03:45:11.639+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-19T03:45:11.669+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-19T03:45:11.682+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
